# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passwordGenerator.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random
import string
from PyQt5.QtGui import QIntValidator

class Ui_MainWindow(object):

    # alert box function - if user doesnt enter any input
    def alertBox(self, title, message):
        window = QtWidgets.QMessageBox()
        window.setWindowTitle(title)
        window.setText(message)
        window.setStandardButtons(QtWidgets.QMessageBox.Ok)
        window.exec_()

    def generateRandomPassword(self):
        if self.passwordLimit.text() == "":
            self.alertBox('Blank Message', 'Please enter your password limit')

        else:
            num = int(self.passwordLimit.text())
            password = ""
            for i in range(num):
                limit = random.randint(0, 61)
                password = password + string.printable[limit]

        self.passwordLimit.clear()
        return self.outputBox.setText(password)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 645)
        MainWindow.setStyleSheet("background-color:black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.appTitle = QtWidgets.QLabel(self.centralwidget)
        self.appTitle.setGeometry(QtCore.QRect(90, 10, 441, 41))
        self.appTitle.setStyleSheet("font-family:Calibri;\n"
"font-weight:bold;\n"
"font-size:28px;\n"
"color:white;")
        self.appTitle.setObjectName("appTitle")
        self.passwordLimitTitle = QtWidgets.QLabel(self.centralwidget)
        self.passwordLimitTitle.setGeometry(QtCore.QRect(80, 100, 441, 41))
        self.passwordLimitTitle.setStyleSheet("font-family:Calibri;\n"
"font-weight:bold;\n"
"font-size:20px;\n"
"color:white;")
        self.passwordLimitTitle.setObjectName("passwordLimitTitle")
        self.passwordLimit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordLimit.setGeometry(QtCore.QRect(80, 161, 451, 41))
        self.passwordLimit.setStyleSheet("font-family:Calibri;\n"
"font-weight:bold;\n"
"padding:8px;\n"
"font-size:18px;\n"
"color:white;\n"
"border:2px solid white;\n"
"border-radius:8px;")
        self.passwordLimit.setObjectName("passwordLimit")
        self.passwordLimit.setValidator(QIntValidator(0,61))
        self.GeneratePasswordButton = QtWidgets.QPushButton(self.centralwidget)
        self.GeneratePasswordButton.clicked.connect(self.generateRandomPassword)
        self.GeneratePasswordButton.setGeometry(QtCore.QRect(80, 250, 451, 51))
        self.GeneratePasswordButton.setStyleSheet("background-color:orange;\n"
"color:white;\n"
"font-family:Calibri;\n"
"font-weight:bold;\n"
"font-size:20px;\n"
"border-radius:8px;")
        self.GeneratePasswordButton.setObjectName("GeneratePasswordButton")
        self.outputBox = QtWidgets.QLineEdit(self.centralwidget)
        self.outputBox.setGeometry(QtCore.QRect(80, 330, 451, 41))
        self.outputBox.setStyleSheet("font-family:Calibri;\n"
"font-weight:bold;\n"
"padding:8px;\n"
"font-size:18px;\n"
"color:white;\n"
"border:2px solid white;\n"
"border-radius:8px;")
        self.outputBox.setObjectName("outputBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Strong Random Password Generator"))
        self.appTitle.setText(_translate("MainWindow", "Strong Random Password Generator"))
        self.passwordLimitTitle.setText(_translate("MainWindow", "Enter your password limit"))
        self.GeneratePasswordButton.setText(_translate("MainWindow", "Generate Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
