# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textToSpeech.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(627, 480)
        MainWindow.setStyleSheet("background-image: url(:/newPrefix/bg.jpg);\n"
"background-position:center bottom;\n"
"background-repeat:no-repeat;\n"
"background-image:fixed;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 30, 241, 51))
        self.label.setStyleSheet("font-family:Calibri;\n"
"font-size:28px;\n"
"font-weight:bold;\n"
"color:white;\n"
"font-image:url(none);")
        self.label.setObjectName("label")
        self.textTitle = QtWidgets.QLabel(self.centralwidget)
        self.textTitle.setGeometry(QtCore.QRect(50, 110, 241, 51))
        self.textTitle.setStyleSheet("font-family:Calibri;\n"
"font-size:20px;\n"
"font-weight:bold;\n"
"color:white;\n"
"font-image:url(none);")
        self.textTitle.setObjectName("textTitle")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(50, 170, 411, 141))
        self.plainTextEdit.setStyleSheet("font-family:Calibri;\n"
"padding:8px;\n"
"font-size:20px;\n"
"font-weight:bold;\n"
"color:orange;\n"
"border:2px solid white;\n"
"border-radius:12px;")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.convertButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertButton.setGeometry(QtCore.QRect(50, 350, 411, 41))
        self.convertButton.setStyleSheet("background-image:url(none);\n"
"background-color:orange;\n"
"font-family:Calibri;\n"
"font-weight:bold;\n"
"font-size:18px;\n"
"color:white;\n"
"border-radius:8px;")
        self.convertButton.setObjectName("convertButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text to Speech"))
        self.label.setText(_translate("MainWindow", "Text to Speech"))
        self.textTitle.setText(_translate("MainWindow", "Write or paste your text"))
        self.convertButton.setText(_translate("MainWindow", "Convert to audio"))
import source


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
